- name: Create and Add Worker VM
  hosts: localhost
  gather_facts: no
  vars:
    new_worker_ip: "{{ ec2_output.instances[0].private_ip }}"
  tasks:
    - name: Launch new EC2 instance
      ec2:
        key_name: li54KeyPair
        instance_type: t2.micro  
        image: ami-0faab6bdbac9486fb
        region: eu-central-1
        group: default
        count: 1
        vpc_subnet_id: subnet-02f46a56bc28de1ba
        assign_public_ip: yes
        instance_tags:
          Name: Assignment_Worker
      register: ec2_output

    - name: Add new worker to existing cluster
      add_host:
        name: "{{ item.private_ip }}"
        groups: workers
      with_items: "{{ ec2_output.instances }}"
